"""digest-database-models-2

Revision ID: 67515cf4e6c4
Revises: 3bbdd9f02edd
Create Date: 2026-02-24 15:50:40.874263

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "67515cf4e6c4"
down_revision: Union[str, Sequence[str], None] = "3bbdd9f02edd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
