"""n01-dbmodels

Revision ID: 6a3e15d8acb1
Revises: 84cb4bc36c10
Create Date: 2026-02-24 16:03:00.433340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a3e15d8acb1'
down_revision: Union[str, Sequence[str], None] = '84cb4bc36c10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_event_digest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('MATCH_COMPLETED', 'PLAYER_PERFORMANCE', name='eventtype'), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscriber_digest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriber_digest_email'), 'subscriber_digest', ['email'], unique=True)
    op.create_table('digest_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscriber_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('PASSED', 'FAILED', 'PARTIAL', name='digeststatus'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['subscriber_id'], ['subscriber_digest.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscription_digest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscriber_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=20), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['subscriber_id'], ['subscriber_digest.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscription_digest')
    op.drop_table('digest_run')
    op.drop_index(op.f('ix_subscriber_digest_email'), table_name='subscriber_digest')
    op.drop_table('subscriber_digest')
    op.drop_table('notification_event_digest')
    # ### end Alembic commands ###
