"""add subscription scheduler fields

Revision ID: c970525c496e
Revises: 6a3e15d8acb1
Create Date: 2026-03-17 20:28:55.520382

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c970525c496e"
down_revision: Union[str, Sequence[str], None] = "6a3e15d8acb1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Create all enum types first before using them
    op.execute("CREATE TYPE digest_status_enum AS ENUM('PASSED', 'FAILED', 'PARTIAL')")
    op.execute(
        "CREATE TYPE event_type_enum AS ENUM('MATCH_COMPLETED', 'PLAYER_PERFORMANCE')"
    )
    op.execute(
        "CREATE TYPE entity_type_enum AS ENUM('MATCH', 'PLAYER', 'TEAM', 'COMPETITION')"
    )

    # Now convert existing columns to use new enum types
    op.execute(
        "ALTER TABLE digest_run ALTER COLUMN status TYPE digest_status_enum USING status::text::digest_status_enum"
    )
    op.execute("DROP TYPE IF EXISTS digeststatus")

    op.execute(
        "ALTER TABLE notification_event_digest ALTER COLUMN event_type TYPE event_type_enum USING event_type::text::event_type_enum"
    )
    op.execute("DROP TYPE IF EXISTS eventtype")

    # Now add new columns that use the enum types
    op.add_column(
        "notification_event_digest",
        sa.Column(
            "entity_type",
            sa.Enum("MATCH", "PLAYER", "TEAM", "COMPETITION", name="entity_type_enum"),
            nullable=False,
        ),
    )

    op.add_column(
        "subscription_digest", sa.Column("entity_id", sa.Integer(), nullable=False)
    )
    op.add_column(
        "subscription_digest",
        sa.Column(
            "entity_type",
            sa.Enum("MATCH", "PLAYER", "TEAM", "COMPETITION", name="entity_type_enum"),
            nullable=False,
        ),
    )
    op.add_column(
        "subscription_digest",
        sa.Column(
            "next_run",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
    )
    op.add_column(
        "subscription_digest",
        sa.Column("last_run", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "subscription_digest",
        sa.Column("day_freq", sa.Integer(), server_default="1", nullable=False),
    )

    op.alter_column(
        "subscription_digest",
        "createdAt",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
    )

    op.create_index(
        op.f("ix_subscription_digest_entity_id"),
        "subscription_digest",
        ["entity_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_subscription_digest_next_run"),
        "subscription_digest",
        ["next_run"],
        unique=False,
    )
    op.create_index(
        op.f("ix_subscription_digest_subscriber_id"),
        "subscription_digest",
        ["subscriber_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_subscription_digest_subscriber_id"), table_name="subscription_digest"
    )
    op.drop_index(
        op.f("ix_subscription_digest_next_run"), table_name="subscription_digest"
    )
    op.drop_index(
        op.f("ix_subscription_digest_entity_id"), table_name="subscription_digest"
    )
    op.alter_column(
        "subscription_digest",
        "createdAt",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
    )
    op.drop_column("subscription_digest", "day_freq")
    op.drop_column("subscription_digest", "last_run")
    op.drop_column("subscription_digest", "next_run")
    op.drop_column("subscription_digest", "entity_type")
    op.drop_column("subscription_digest", "entity_id")

    op.execute("CREATE TYPE eventtype AS ENUM('MATCH_COMPLETED', 'PLAYER_PERFORMANCE')")
    op.execute(
        "ALTER TABLE notification_event_digest ALTER COLUMN event_type TYPE eventtype USING event_type::text::eventtype"
    )
    op.execute("DROP TYPE IF EXISTS event_type_enum")

    op.drop_column("notification_event_digest", "entity_type")

    op.execute("CREATE TYPE digeststatus AS ENUM('PASSED', 'FAILED', 'PARTIAL')")
    op.execute(
        "ALTER TABLE digest_run ALTER COLUMN status TYPE digeststatus USING status::text::digeststatus"
    )
    op.execute("DROP TYPE IF EXISTS digest_status_enum")
    # ### end Alembic commands ###
