"""adjusting-payload

Revision ID: e832ebd379df
Revises: cd0ddfdf8a61
Create Date: 2026-04-08 14:07:39.409541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e832ebd379df'
down_revision: Union[str, Sequence[str], None] = 'cd0ddfdf8a61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('entity_cache', 'payload',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=False,
               postgresql_using='payload::json')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('entity_cache', 'payload',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               postgresql_using='payload::text')
    # ### end Alembic commands ###
